# Generated by Django 4.2.6 on 2024-08-16 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_department_services_department_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.department'),
        ),
    ]
