# Generated by Django 4.2.6 on 2024-08-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_department_services_service_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(null=True, upload_to='department'),
        ),
    ]
