# Generated by Django 4.2.6 on 2024-08-24 13:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name'),
        ),
    ]
